service: finnhub-api
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x

  websocketsApiName: ${self:service}
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body
  websocketsDescription: Finnhub Websocket API
  
  logs:
    frameworkLambda: true
    websocket: true
  
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
    CONNECTION_TABLE: ${self:resources.Resources.FinnhubApiWsConnectionTable.Properties.TableName}
  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:GetItem'
            - 'dynamodb:DeleteItem'
            - 'dynamodb:Scan'
          Resource:
            - Fn::GetAtt: [FinnhubApiWsConnectionTable, Arn]
        - Effect: Allow
          Action:
            - 'execute-api:ManageConnections'
          Resource:
            - 'arn:aws:execute-api:*:*:**/@connections/*'

package:
  individually: true

functions:
  connect:
    handler: ./src/functions/handler.connect
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: ./src/functions/handler.disconnect
    events:
      - websocket:
          route: $disconnect
  default:
    handler: handler.defaultHandler
    events:
      - websocket:
          route: $default
  send:
    handler: handler.send
    events:
      - websocket:
          route: send
          routeResponseSelectionExpression: $default

resources:
  Resources:
    FinnhubApiWsConnectionTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: FinnhubApiWsConnectionTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: 'connectionId'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'connectionId'
            KeyType: 'HASH'
